#---------------------------------#
#      environment configuration  #
#---------------------------------#
os: WMF 5

version: 10.0.10586.{build}

configuration: Release

platform: x86

install:
   - git clone https://github.com/Microsoft/Windows-driver-samples.git

#---------------------------------#
#      build configuration        #
#---------------------------------#

build:
  project: Windows-driver-samples\setup\devcon\devcon.vcxproj
  verbosity: normal

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script: none

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
  - ps: |
