#---------------------------------#
#      environment configuration  #
#---------------------------------#
os: WMF 5

version: 10.0.10586.{build}

configuration: Release

platform: Any CPU

install:
   - git clone https://github.com/Microsoft/Windows-driver-samples.git

#---------------------------------#
#      build configuration        #
#---------------------------------#

build_script:
   - cmd: msbuild "Windows-driver-samples\setup\devcon\devcon.vcxproj" /p:Configuration=Release;Platform=Win32 /t:Clean;Build /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
   - cmd: msbuild "Windows-driver-samples\setup\devcon\devcon.vcxproj" /p:Configuration=Release;Platform=x64 /t:Clean;Build /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#      test configuration         #
#---------------------------------#

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
  - ps: |
      # Create Chocolately Package

      # Because the bits need to be signed by MSFT, we are no longer using
      # the compiled version, but instead we'll use the one from the WDK.
      # The only problem is that the WDK versions aren't signed by MSFT either.

      # Copy-Item -Path .\Windows-driver-samples\setup\devcon\Release\devcon.exe `
      #  -Destination .\devcon.portable\Devcon32.exe
      # Copy-Item -Path .\Windows-driver-samples\setup\devcon\x64\Release\devcon.exe `
      #  -Destination .\devcon.portable\Devcon64.exe

      Set-Location -Path .\devcon.portable\
      (Get-Content '.\devcon.portable.nuspec' -Raw).Replace("<version>1.0</version>", "<version>$($env:APPVEYOR_BUILD_VERSION)</version>") | Out-File '.\devcon.portable.nuspec'
      Choco Pack
      Push-AppveyorArtifact ".\devcon.portable.$($ENV:APPVEYOR_BUILD_VERSION).nupkg"
